version: '3.1'

services:
  coder:
    image: pxlart/coder
    entrypoint:
      - "dumb-init"
      - "code-server"
      - "--allow-http"
      - "--no-auth"
      - "--user-data-dir"
      - "/home/coder/userdata"
    ports:
      - 3000:8443
      - 3001:8000
      - 3002:9000
    volumes:
      - /home/michael_rhema/projects:/home/coder/project
      - /home/michael_rhema/coder-settings:/home/coder/userdata
